export const blogs = [
  {
    id: "1",
    img: "/imgs/open-pipe-2.jpg",
    title: "Lorem Ipsum Revelat Potens",
    type: "Technical Articles",
    date: "05/07/24",
  },
  {
    id: "2",
    img: "/imgs/open-pipe-3.png",
    title: "Lorem Ipsum Revelat Potens",
    type: "Announcements",
    date: "12/06/25",
  },
  {
    id: "3",
    img: "/imgs/open-pipe.png",
    title: "Lorem Ipsum Revelat Potens",
    type: "Technical Articles",
    date: "23/03/23",
  },
  {
    id: "4",
    img: "/imgs/open-pipe-3.png",
    title: "Lorem Ipsum Revelat Potens",
    type: "Announcements",
    date: "12/06/25",
  },
  {
    id: "5",
    img: "/imgs/sprinkler.png",
    title: "Lorem Ipsum Revelat Potens",
    type: "Technical Articles",
    date: "23/03/23",
  },
  {
    id: "6",
    img: "/imgs/pipe.png",
    title: "Lorem Ipsum Revelat Potens",
    type: "Announcements",
    date: "12/06/25",
  },
  {
    id: "7",
    img: "/imgs/open-pipe.png",
    title: "Lorem Ipsum Revelat Potens",
    type: "Technical Articles",
    date: "23/03/23",
  },
  {
    id: "8",
    img: "/products/1.jpg",
    title: "Lorem Ipsum Revelat Potens",
    type: "Announcements",
    date: "12/06/25",
  },
  {
    id: "9",
    img: "/products/2.jpg",
    title: "Lorem Ipsum Revelat Potens",
    type: "Technical Articles",
    date: "23/03/23",
  },
];
